// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: type1.proto

package tutorial1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExampleEnum1 int32

const (
	ExampleEnum1_OPTION_ONE  ExampleEnum1 = 0
	ExampleEnum1_OPTION_TWO  ExampleEnum1 = 1
	ExampleEnum1_OPTION_FOUR ExampleEnum1 = 2
)

// Enum value maps for ExampleEnum1.
var (
	ExampleEnum1_name = map[int32]string{
		0: "OPTION_ONE",
		1: "OPTION_TWO",
		2: "OPTION_FOUR",
	}
	ExampleEnum1_value = map[string]int32{
		"OPTION_ONE":  0,
		"OPTION_TWO":  1,
		"OPTION_FOUR": 2,
	}
)

func (x ExampleEnum1) Enum() *ExampleEnum1 {
	p := new(ExampleEnum1)
	*p = x
	return p
}

func (x ExampleEnum1) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExampleEnum1) Descriptor() protoreflect.EnumDescriptor {
	return file_type1_proto_enumTypes[0].Descriptor()
}

func (ExampleEnum1) Type() protoreflect.EnumType {
	return &file_type1_proto_enumTypes[0]
}

func (x ExampleEnum1) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExampleEnum1.Descriptor instead.
func (ExampleEnum1) EnumDescriptor() ([]byte, []int) {
	return file_type1_proto_rawDescGZIP(), []int{0}
}

type Person struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	ExampleEnum   ExampleEnum1           `protobuf:"varint,3,opt,name=example_enum,json=exampleEnum,proto3,enum=tutorial1.ExampleEnum1" json:"example_enum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Person) Reset() {
	*x = Person{}
	mi := &file_type1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_type1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_type1_proto_rawDescGZIP(), []int{0}
}

func (x *Person) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Person) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Person) GetExampleEnum() ExampleEnum1 {
	if x != nil {
		return x.ExampleEnum
	}
	return ExampleEnum1_OPTION_ONE
}

var File_type1_proto protoreflect.FileDescriptor

const file_type1_proto_rawDesc = "" +
	"\n" +
	"\vtype1.proto\x12\ttutorial1\"h\n" +
	"\x06Person\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12:\n" +
	"\fexample_enum\x18\x03 \x01(\x0e2\x17.tutorial1.ExampleEnum1R\vexampleEnum*?\n" +
	"\fExampleEnum1\x12\x0e\n" +
	"\n" +
	"OPTION_ONE\x10\x00\x12\x0e\n" +
	"\n" +
	"OPTION_TWO\x10\x01\x12\x0f\n" +
	"\vOPTION_FOUR\x10\x02B\rZ\v./tutorial1b\x06proto3"

var (
	file_type1_proto_rawDescOnce sync.Once
	file_type1_proto_rawDescData []byte
)

func file_type1_proto_rawDescGZIP() []byte {
	file_type1_proto_rawDescOnce.Do(func() {
		file_type1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_type1_proto_rawDesc), len(file_type1_proto_rawDesc)))
	})
	return file_type1_proto_rawDescData
}

var file_type1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_type1_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_type1_proto_goTypes = []any{
	(ExampleEnum1)(0), // 0: tutorial1.ExampleEnum1
	(*Person)(nil),    // 1: tutorial1.Person
}
var file_type1_proto_depIdxs = []int32{
	0, // 0: tutorial1.Person.example_enum:type_name -> tutorial1.ExampleEnum1
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_type1_proto_init() }
func file_type1_proto_init() {
	if File_type1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_type1_proto_rawDesc), len(file_type1_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_type1_proto_goTypes,
		DependencyIndexes: file_type1_proto_depIdxs,
		EnumInfos:         file_type1_proto_enumTypes,
		MessageInfos:      file_type1_proto_msgTypes,
	}.Build()
	File_type1_proto = out.File
	file_type1_proto_goTypes = nil
	file_type1_proto_depIdxs = nil
}
