# This example creates simple agent using gpt-oss model  
example01-step1:
	go run cmd/examples/example-01/step-1/main.go

example01-step2:
	go run cmd/examples/example-01/step-2/main.go

example01-step3:
	go run cmd/examples/example-01/step-3/main.go

example01-step4:
	go run cmd/examples/example-01/step-4/main.go